CREATE DATABASE CAPSTONE;
USE CAPSTONE;

CREATE TABLE INVENTORY (
    PO_NUMBER VARCHAR(20) PRIMARY KEY,
    DATE_DELIVERED DATE,
    SUPPLIER VARCHAR(100),
    ITEM_NAME VARCHAR(100),
    ITEM_TYPE VARCHAR(50),
    UNIT VARCHAR(50),
    QUANTITY INT,
    UNIT_COUNT INT,
    PO_DESCRIPTION TEXT,
    SECTION VARCHAR(100),
    RESPONSIBLE VARCHAR(100),
    ITEM_STATUS VARCHAR(50)
);

CREATE TABLE PAR (
    PO_NUMBER VARCHAR(20) PRIMARY KEY,
    PROPERTY_NUMBER VARCHAR(20),
    PAR_NUMBER VARCHAR(20),
    QUANTITY INT,
    UNIT INT,
    PAR_Description TEXT,
    FOREIGN KEY (PO_NUMBER) REFERENCES INVENTORY(PO_NUMBER)
);

CREATE TABLE RIS (
	PO_NUMBER VARCHAR(20) PRIMARY KEY,
    RIS_NUMBER VARCHAR(20),
    SAI_NUMBER VARCHAR(20),
    RIS_DATE DATE,
    SAI_DATE DATE,
    ACCOUNT_TITLE VARCHAR(100),
    ACCOUNT_CODE VARCHAR(20),
    DIVISION VARCHAR(100),
    OFFICE VARCHAR(100),
    RESPONSIBILITY_CENTER VARCHAR(100),
    SUPPLY_NUMBER VARCHAR(20),
    QUANTITY INT,
    UNIT VARCHAR(50),
    RIS_DESCRIPTION TEXT,
    UNIT_COST DECIMAL(10, 2),
    ESTIMATED_COST DECIMAL(10, 2),
    PURPOSE_OF_USE VARCHAR(200),
    REQUESTOR_NAME VARCHAR(100),
    APPROVER_NAME VARCHAR(100),
    ISSUER_NAME VARCHAR(100),
    RECEIVER_NAME VARCHAR(100),
    GSO_OFFICER_NAME VARCHAR(100),
    DEPARTMENT VARCHAR(100),
    FOREIGN KEY (PO_NUMBER) REFERENCES INVENTORY(PO_NUMBER)
);


CREATE TABLE ICS (
    PO_NUMBER VARCHAR(20),
    ENTITY_NAME VARCHAR(100),
    FUND_CLUSTER VARCHAR(100),
    QUANTITY INT,
    UNIT VARCHAR(50),
    UNIT_COST DECIMAL(10, 2),
    TOTAL_COST DECIMAL(10, 2),
    ICS_DESCRIPTION TEXT,
    ITEM_NUMBER VARCHAR(20),
    ESTIMATED_USEFUL_LIFE INT,
    RECEIVED_FROM_NAME VARCHAR(100),
    RECEIVED_FROM_DEPARTMENT VARCHAR(100),
    RECEIVED_BY_NAME VARCHAR(100),
    RECEIVED_BY_DEPARTMENT VARCHAR(100),
    DATE_RECEIVED DATE,
    FOREIGN KEY (PO_NUMBER) REFERENCES INVENTORY(PO_NUMBER)
);

CREATE TABLE GSO_OFFICER (
    OFFICER_NAME VARCHAR(100) PRIMARY KEY,
    USERNAME VARCHAR(50),
    OFFICER_PASSWORD VARCHAR(50),
    DEPARTMENT VARCHAR(100)
);

CREATE TABLE TEMP (
    PO_NUMBER VARCHAR(20) PRIMARY KEY
);

CREATE TABLE TEMP (
    PO_NUMBER VARCHAR(20) PRIMARY KEY
);

CREATE TABLE TEMP (
    PO_NUMBER VARCHAR(20) PRIMARY KEY
);

CREATE TABLE TEMP (
    PO_NUMBER VARCHAR(20) PRIMARY KEY
);


